import Head from "next/head";
import Image from "next/image";
import styles from "@/styles/Home.module.css";
import NavBar from "@/components/molecules/navbar";
import { useContext } from "react";
import StyleContext from "@/components/context/styleContext";
import { MainPart } from "@/components/organisms/mainPart";

export default function Home() {
  const { menuOpen, setMenuOpen } = useContext(StyleContext);
  return (
    <>
      <Head>
        <title>Shyngys Karishev</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={menuOpen ? "blur" : ""}>
        <NavBar />
        <MainPart />
      </main>
    </>
  );
}
